// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Payment.Application.Abstractions.Persistence;
using System;
using System.Collections.Generic;
using PaymentModel = Payment.Domain.Entities;

namespace Payment.Infrastructure.Models;

public partial class PaymentDbContext : DbContext, IPaymentDbContext
{
    public PaymentDbContext(DbContextOptions<PaymentDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<PaymentModel.Payment> Payments { get; set; }

    public virtual DbSet<PaymentModel.PaymentEvent> PaymentEvents { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PaymentModel.Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Payments__3214EC073BD8C176");

            entity.ToTable("Payments", "payment");

            entity.HasIndex(e => e.OrderId, "IX_Payments_OrderId");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ClientSecret).HasMaxLength(255);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValue("VND")
                .IsFixedLength();
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.UpdatedAtUtc).HasPrecision(0);
        });

        modelBuilder.Entity<PaymentModel.PaymentEvent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentE__3214EC078AD04B1B");

            entity.ToTable("PaymentEvents", "payment");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.EventType)
                .IsRequired()
                .HasMaxLength(60);

            entity.HasOne(d => d.Payment).WithMany(p => p.PaymentEvents)
                .HasForeignKey(d => d.PaymentId)
                .HasConstraintName("FK__PaymentEv__Payme__0C85DE4D");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}