// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Orchestrator.Worker.Models;

public partial class OrderSagaState
{
    public Guid Id { get; set; }

    public Guid OrderId { get; set; }

    public Guid? CustomerId { get; set; }

    public decimal Amount { get; set; }

    public string Status { get; set; }

    public bool InventoryReserved { get; set; }

    public bool PaymentCompleted { get; set; }

    public bool IsFailed { get; set; }

    public string FailReason { get; set; }

    public int RetryCount { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public virtual ICollection<OrderSagaItem> OrderSagaItems { get; set; } = new List<OrderSagaItem>();
}