// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Orchestrator.Worker.Models;

public partial class OrderSagaItem
{
    public Guid Id { get; set; }

    public Guid SagaStateId { get; set; }

    public Guid ProductId { get; set; }

    public int Quantity { get; set; }

    public int? ReservedQuantity { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual OrderSagaState SagaState { get; set; }
}