// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Orchestrator.Worker.Models;

public partial class SagaDbContext : DbContext
{
    public SagaDbContext(DbContextOptions<SagaDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<OrderSagaItem> OrderSagaItems { get; set; }

    public virtual DbSet<OrderSagaState> OrderSagaStates { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<OrderSagaItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderSag__3214EC07E8CC6BF9");

            entity.ToTable("OrderSagaItems", "saga");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.UpdatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.SagaState).WithMany(p => p.OrderSagaItems)
                .HasForeignKey(d => d.SagaStateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderSagaItems_SagaState");
        });

        modelBuilder.Entity<OrderSagaState>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderSag__3214EC07F5BE0043");

            entity.ToTable("OrderSagaStates", "saga");

            entity.HasIndex(e => e.OrderId, "UQ__OrderSag__C3905BCE4B789C52").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.FailReason).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("Pending");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}